/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package microproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;

/**
 *
 * @author Rushikesh
 */
public class SalesReport extends javax.swing.JFrame {

    /**
     * Creates new form SalesReport
     */
    public SalesReport() {
        initComponents();
        this.setLocationRelativeTo(null);
        Connect();
        tableupdategg();
    }
    
    Connection conn;
    PreparedStatement pat;    
    String DateFromAA;
    String DateToAA;
     public void Connect() {
     
        try {
           Class.forName("com.mysql.cj.jdbc.Driver");
             String url = "jdbc:mysql://localhost:3306/miniproject";
            String user = "root";
            String password = "Dada@2003";
            conn = DriverManager.getConnection(url, user, password); 
          
            System.out.println("connectted");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CreateMenuActivity.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    
    public void tableupdategg(){
     int cc;
      
        try {
            pat = conn.prepareStatement("select * from savedbilldata;");
            ResultSet RS = pat.executeQuery();
            ResultSetMetaData RSMD = RS.getMetaData();
            cc = RSMD.getColumnCount();
            DefaultTableModel DTM = (DefaultTableModel) ReportDataTable.getModel();
            DTM.setRowCount(0);
            
            while(RS.next()){
                Vector  v2 = new Vector();
                
                for(int i = 0;i <= cc ; i++){
                 v2.add(RS.getString("Billno"));
                 v2.add(RS.getString("Datee"));
                 v2.add(RS.getString("CustName"));
                 v2.add(RS.getString("FoodName"));
                 v2.add(RS.getString("Qty"));
                 v2.add(RS.getString("Price"));
                }
                DTM.addRow(v2); 
                /*DefaultTableModel model = (DefaultTableModel) StudentDataTable.getModel();
                   model.addRow(new Object[]{srno,name,roll,clas});*/
           }
            
        } catch (SQLException ex) {
            Logger.getLogger(CreateMenuActivity.class.getName()).log(Level.SEVERE, null, ex);
        } 
            System.out.println("connectted");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReportDataTable = new javax.swing.JTable();
        GoBack = new javax.swing.JButton();
        QuantityAnalysis = new javax.swing.JButton();
        SalesAnalysis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SALES ANALYSIS");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("SALES DATA : ");

        ReportDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Bill No", "Date", "Customer Name", "Ordered Food", "Quantity", "Total Amount"
            }
        ));
        ReportDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportDataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ReportDataTable);
        if (ReportDataTable.getColumnModel().getColumnCount() > 0) {
            ReportDataTable.getColumnModel().getColumn(2).setMinWidth(200);
        }

        GoBack.setBackground(new java.awt.Color(255, 153, 0));
        GoBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GoBack.setText("GO BACK");
        GoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackActionPerformed(evt);
            }
        });

        QuantityAnalysis.setBackground(new java.awt.Color(204, 255, 51));
        QuantityAnalysis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QuantityAnalysis.setText("REPORT ACCORDING TO QUANTY");
        QuantityAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityAnalysisActionPerformed(evt);
            }
        });

        SalesAnalysis.setBackground(new java.awt.Color(102, 255, 0));
        SalesAnalysis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SalesAnalysis.setText("REPORT ACCORDING TO SALES");
        SalesAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesAnalysisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(SalesAnalysis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuantityAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                        .addComponent(GoBack)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(QuantityAnalysis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(GoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addComponent(SalesAnalysis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void QuantityAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityAnalysisActionPerformed
        String query = "SELECT Datee,Qty FROM savedbilldata";
        JDBCCategoryDataset  dataset;
        try {
            dataset = new JDBCCategoryDataset(conn,query);            
            JFreeChart chart = ChartFactory.createLineChart("Sales Report", "Date","Quantity" , dataset, PlotOrientation.VERTICAL, false, true, true);
            BarRenderer ren = null;
            CategoryPlot plt = null;
            ren = new BarRenderer();
            ChartFrame frame = new ChartFrame("Sales Report", chart);
            frame.setLocation(270, 120);
            frame.setSize(800,600);
            frame.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(SalesReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_QuantityAnalysisActionPerformed

    private void GoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackActionPerformed
        AdminActivity ma = new AdminActivity();
        this.setVisible(false);   
        dispose();
        ma.setVisible(true);        
    }//GEN-LAST:event_GoBackActionPerformed
      
    private void SalesAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesAnalysisActionPerformed

        String query = "SELECT Datee,Price FROM savedbilldata";        
        JDBCCategoryDataset  dataset;
        try {                
            dataset = new JDBCCategoryDataset(conn,query);            
            JFreeChart chart = ChartFactory.createLineChart("Sales Report", "Date","Total Sales In Rs" , dataset, PlotOrientation.VERTICAL, false, true, true);
            BarRenderer ren = null;
            CategoryPlot plt = null;
            ren = new BarRenderer();
            ChartFrame frame = new ChartFrame("Sales Report", chart);
            frame.setLocation(270, 120);
            frame.setSize(800,600);
            frame.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(SalesReport.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,DateFromAA+" "+DateToAA,
                        "Data Report Status", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SalesAnalysisActionPerformed

    private void ReportDataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportDataTableMouseClicked
       /*/***/
    }//GEN-LAST:event_ReportDataTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoBack;
    private javax.swing.JButton QuantityAnalysis;
    private javax.swing.JTable ReportDataTable;
    private javax.swing.JButton SalesAnalysis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
